---
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-attachments:persistence:file:default:1.0"
  path: "./data/attachments.json"

- descriptor: "pip-services-attachments:controller:default:default:1.0"

- descriptor: "pip-services-attachments:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080
